### ISSUE TITLE
[Feature Request]: The accordion can toggle smoothly when opening ([open] state).

### ISSUE THREAD

**Issue by keremzor** [Trendyol/grace#1077]
### Describe the problem or use case

https://github.com/user-attachments/assets/a8e8980c-85d5-4df9-84b2-c1968b00fd06

There is a slight inconsistency in the opening behavior of the `.accordion-content` div when the accordion component is in the `[open]` state. While this isn’t technically a bug, it’s possible to make the toggle transition smoother for a better user experience.

### Proposed solution

This is not a direct solution, but it's an approach that can be explored further to reach a proper outcome.

```css
.accordion-content {
  max-height: 0;
  overflow: hidden;
  opacity: 0;
  transition: 
    max-height 0.5s ease,
    opacity 0.5s ease;
}
```
```css
details[open] .accordion-content {
  max-height: 500px; /* dynamic value can be given */
  opacity: 1;
}
```
